title: "MW119/MW65 - Causal machine Learning   "
contributors: "Prof. Dr. Jannis Kück"
affiliation: "Düsseldorf Institute for Competition Economics (DICE)"

logo: "/assets/img/Logo_HHU.jpg"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

